export type User = {
  user_id: string;
  username: string;
  first_name: string;
  middle_name: string | null;
  last_name: string;
  suffix: string | null;
  sex: string;
  email: string;
  contact_number: string;
  emergency_contact_name: string | null;
  emergency_contact: string | null;
  address: string;
  birthdate: string;
  role: string;
  department: string | null;
  employment_status: string | null;
  date_hired: string;
  shift_start: string;
  shift_end: string;
  profile_photo: string | null;
  active: boolean;
  account_status: boolean;
  created_at: string;
  updated_at: string;
};