import type { ReportTemplate } from "./types";

export const SAMPLE_CBC_TEMPLATE: ReportTemplate = {
  fixtureId: "sample-cbc",
  name: "Complete Blood Count",
  description:
    "Routine automated hematology examination measuring red and white blood cells, hemoglobin, hematocrit, and platelet indices.",
  category: "Hematology",
  status: "Published",
  createdBy: "Dr. LeBron R. James",
  usageCount: 123,
  lastUpdated: "5 mins ago",
  components: [
    {
      id: "comp-cbc-1",
      type: "section_header",
      label: "HEMATOLOGY EXAMINATION",
      fieldKey: "hematology_header",
      order: 1,
      settings: {
        sectionHeader: "HEMATOLOGY EXAMINATION",
        alignment: "left",
        showInPreview: true,
        width: "FULL",
      },
      validation: {},
    },
    {
      id: "comp-cbc-2",
      type: "number_field",
      label: "Hemoglobin",
      fieldKey: "hemoglobin",
      order: 2,
      settings: {
        placeholder: "Enter value",
        unit: "g/dL",
        referenceRange: "12.0 - 16.0",
        required: true,
        showInPreview: true,
        width: "1/2",
        alignment: "left",
      },
      validation: {
        required: true,
        inputType: "Number",
        minValue: 0,
        maxValue: 30,
        decimalPlaces: 1,
        refLow: 12.0,
        refNormal: 14.0,
        refHigh: 16.0,
        flagLabels: {
          low: "Low",
          normal: "Normal",
          high: "High",
        },
        customMessage: "Hemoglobin value must be within normal clinical range.",
      },
    },
    {
      id: "comp-cbc-3",
      type: "number_field",
      label: "Hematocrit",
      fieldKey: "hematocrit",
      order: 3,
      settings: {
        placeholder: "Enter value",
        unit: "%",
        referenceRange: "37.0 - 48.0",
        required: true,
        showInPreview: true,
        width: "1/2",
        alignment: "left",
      },
      validation: {
        required: true,
        inputType: "Number",
        minValue: 10,
        maxValue: 70,
        decimalPlaces: 1,
        refLow: 37.0,
        refNormal: 42.0,
        refHigh: 48.0,
      },
    },
    {
      id: "comp-cbc-4",
      type: "number_field",
      label: "WBC Count",
      fieldKey: "wbc_count",
      order: 4,
      settings: {
        placeholder: "Enter value",
        unit: "x10^9/L",
        referenceRange: "4.5 - 11.0",
        required: true,
        showInPreview: true,
        width: "1/2",
        alignment: "left",
      },
      validation: {
        required: true,
        inputType: "Number",
        minValue: 0,
        maxValue: 100,
        decimalPlaces: 2,
      },
    },
    {
      id: "comp-cbc-5",
      type: "number_field",
      label: "Platelet Count",
      fieldKey: "platelet_count",
      order: 5,
      settings: {
        placeholder: "Enter value",
        unit: "x10^9/L",
        referenceRange: "150 - 450",
        required: true,
        showInPreview: true,
        width: "1/2",
        alignment: "left",
      },
      validation: {
        required: true,
        inputType: "Number",
        minValue: 10,
        maxValue: 1500,
      },
    },
    {
      id: "comp-cbc-6",
      type: "line_divider",
      label: "Divider",
      fieldKey: "divider_1",
      order: 6,
      settings: {
        dividerStyle: "solid",
        showInPreview: true,
        width: "FULL",
      },
      validation: {},
    },
    {
      id: "comp-cbc-7",
      type: "table",
      label: "Differential Count",
      fieldKey: "diff_count_table",
      order: 7,
      settings: {
        width: "FULL",
        showInPreview: true,
        tableColumns: [
          { id: "col_1", header: "Segmenters (%)", type: "number" },
          { id: "col_2", header: "Lymphocytes (%)", type: "number" },
          { id: "col_3", header: "Monocytes (%)", type: "number" },
          { id: "col_4", header: "Eosinophils (%)", type: "number" },
          { id: "col_5", header: "Basophils (%)", type: "number" },
        ],
      },
      validation: {
        tableRules: {
          minRows: 1,
          maxRows: 5,
        },
      },
    },
    {
      id: "comp-cbc-8",
      type: "static_text",
      label: "Technical Note",
      fieldKey: "tech_note",
      order: 8,
      settings: {
        staticText:
          "Test performed using automated hematology analyzer. Confirmed with peripheral blood smear examination when clinically indicated.",
        width: "FULL",
        alignment: "left",
        showInPreview: true,
      },
      validation: {},
    },
  ],
};

export const INITIAL_TEMPLATES_LIST: ReportTemplate[] = [SAMPLE_CBC_TEMPLATE];
